sudo: false
language: node_js

notifications:
  email: false

node_js:
  - "stable"

before_install:
  - npm i -g npm@latest

install:
  - npm install

before_script:
  - npm run lint
  - npm run build

script:
  - npm run $COMMAND

after_success:
  - npm run autorelease

env:
  matrix:
    - CLIENT=node COMMAND=test-pouchdb
    - CLIENT=node SERVER_ARGS=--in-memory COMMAND=test-pouchdb
    - CLIENT=node SERVER_ARGS=--sqlite COMMAND=test-pouchdb

    # Test against the couchdb harness
    - COMMAND=test-couchdb

matrix:
  allow_failures:
    - env: COMMAND=test-couchdb

branches:
  only:
    - "master"
